// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCldSOSaJilf5xHtwtzFztMtPVJWwkpFBg',
    appId: '1:55640862757:web:e5948dee12051096988fcc',
    messagingSenderId: '55640862757',
    projectId: 'b-store-70e23',
    authDomain: 'b-store-70e23.firebaseapp.com',
    storageBucket: 'b-store-70e23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRezVcb0sNdznQ1Y9jDaKTqYJnNio_314',
    appId: '1:55640862757:android:fc2691dddc0a6c22988fcc',
    messagingSenderId: '55640862757',
    projectId: 'b-store-70e23',
    storageBucket: 'b-store-70e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfCb2hVgpY43RAzIrgv30PeFS49uE_nVE',
    appId: '1:55640862757:ios:050abf1402e455da988fcc',
    messagingSenderId: '55640862757',
    projectId: 'b-store-70e23',
    storageBucket: 'b-store-70e23.appspot.com',
    androidClientId: '55640862757-hdc424ueos577b99r42o56585ua3mlhn.apps.googleusercontent.com',
    iosClientId: '55640862757-dpu3fr18vt7afaa1ghtvij1utd6q697r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bStore',
  );
}
